export const GET_CARD_OK = 'GET_CARD_OK'
export const GET_PREV_CARD_OK = 'GET_PREV_CARD_OK'
export const GET_CARD_NOK = 'GET_CARD_NOK'

export const GET_BASIC_INFO_OK = 'GET_BASIC_INFO_OK'
export const GET_BASIC_INFO_NOK = 'GET_BASIC_INFO_NOK'

export const GET_RACE_ODDS_OK = 'GET_RACE_ODDS_OK'
export const GET_RACE_ODDS_NOK = 'GET_RACE_ODDS_NOK'

export const OPEN_CARD_OK = 'OPEN_CARD_OK'

export const GET_RACE_ANALYSIS_OK = 'GET_RACE_ANALYSIS_OK'
export const GET_RACE_ANALYSIS_NOK = 'GET_RACE_ANALYSIS_NOK'
export const GET_RACE_ANALYSIS_NO_RESULT = 'GET_RACE_ANALYSIS_NO_RESULT'


export const GET_CURRENT_RACE_ID = 'GET_CURRENT_RACE_ID'
export const SET_CURRENT_RACE_ID = 'SET_CURRENT_RACE_ID'