export const GET_CARD_OK = 'GET_CARD_OK'
export const GET_PREV_CARD_OK = 'GET_PREV_CARD_OK'
export const GET_CARD_NOK = 'GET_CARD_NOK'

export const GET_BASIC_INFO_OK = 'GET_BASIC_INFO_OK'
export const GET_BASIC_INFO_NOK = 'GET_BASIC_INFO_NOK'

export const GET_RACE_ODDS_OK = 'GET_RACE_ODDS_OK'
export const GET_RACE_ODDS_NOK = 'GET_RACE_ODDS_NOK'
